### PR TITLE
Fix sources path in source maps (fixes #56)

### LINKED ISSUE #56: Uglify not working with gulp-sourcemaps
When I try and uglify my code without concatenating it and then generate source maps I get an error message like:

```
gulp-sourcemap-write: source file not found:C:\Rob\Dropbox\Repos\gulpTest\?
```

my gulp task looks like this

```JavaScript
gulp.task('js', function () {
    return gulp.src('app.js')
        .pipe(sourcemaps.init())
        .pipe(uglify())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('build'));
});
```

I'm using the following versions of npm modules

```JSON
  "dependencies": {
    "gulp": "3.8.8",
    "gulp-uglify": "1.0.1",
    "gulp-sourcemaps": "1.1.5"
  }
```

There is a zipped up version of the project here https://dl.dropboxusercontent.com/u/20066539/Forum%20Links/Other/gulpTest.zip

This issue is related to https://github.com/floridoo/gulp-sourcemaps/issues/34

### PR DESCRIPTION
**Pull request by floridoo**
Fixes the problems related to Uglify setting the `sources` array to `['?']`. See comments below.

### CODE REVIEW

**Comment by stevelacy** [comment]
:+1:

**Comment by ilanbiala** [comment]
@floridoo what is the effect of this for users?

**Comment by schnittstabil** [comment]
@ilanbiala: IMHO, this PR probably fixes #56 - but I've only read the title... ;-)

File: index.js [hunk 1]
```diff
@@ -82,7 +81,9 @@ module.exports = function(opt) {
 		file.contents = mangled.code;
 
 		if (file.sourceMap) {
-			applySourceMap(file, mangled.map);
+			var sourceMap = JSON.parse(mangled.map);
+			sourceMap.sources = [file.relative];
```
Comment (terinjokes) [inline index.js]: @floridoo Does this work if the incoming file has multiple sources?

Comment (floridoo) [inline index.js]: @terinjokes Yes, it does. The sources array set here is just for the source map of this transformation. It is merged with the source map of the incoming file in `applySourceMap`. The incoming source map can have an array of multiple sources.

**Comment by stevelacy** [comment]
:smile:

**Comment by jmm** [comment]
@terinjokes This is the same solution* that I [proposed on 12/16](https://github.com/terinjokes/gulp-uglify/issues/56#issuecomment-67209395)* in #56 (where possible solutions seemed to be under discussion) after putting a lot of effort into debugging this, and you never even commented on it before accepting this pull request or closing #56. That's very frustrating. What's up with that -- did it just slip through the cracks?

*With these exceptions:

* I didn't do anything with `options.inSourceMap`, but with my original test case the output with a5f0fa1 and [my branch](https://github.com/jmm/gulp-uglify/compare/jmm:b3eae16...jmm:2ed07e5) is identical. I haven't looked into what the significance of that is so I don't know if it plays a role in fixing #56 or it's an unrelated correction.

* They each fall down in a different way in the case of a rename, e.g.

```js
gulp.task('default', function () {
  return gulp
    .src(['./src/before.js'])
    .pipe(sourcemaps.init())
      .pipe(require('gulp-rename')(function (path) {
        path.basename = 'after';
      }))
      .pipe(uglify())
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('./dist'));
});
```

With my patch(and testing in Chrome 36 / Win 7 x64) the original name is displayed for the source script and breakpoints, etc. work. With the patch from this pull request the renamed name is displayed for the source script, but it's displayed as a blank file, so it's unusable.

**Comment by terinjokes** [comment]
@jmm The real issue is that UglifyJS produces bad source maps, that we've tried to fix on our end several times, and each makes gulp-uglify work better for some people, and makes it worse for others.

I'm convinced at this point that it's a lose-lose situation for me until upstream fixes it.

**Comment by jmm** [comment]
@terinjokes Yes, I understand, that's why when I mentioned this approach in #56 it was as a "workaround to implement in gulp-uglify as a temporary fix."

> I'm convinced at this point that it's a lose-lose situation for me until upstream fixes it.

I see what you mean. That's too bad considering how maintenance seems to be going on that project.

For anyone reading my comments in this thread, [I see now](https://github.com/terinjokes/gulp-uglify/issues/56#issuecomment-70704812) that this idea was already discussed by @terinjokes and @floridoo in #56 before I brought it up -- I just lost track of that (by the time I got to the end of the thread I probably figured that ideas that had been discussed 3 months prior hadn't panned out and then started debugging the problem for myself and didn't realize I had circled back around to an idea that had already been discussed.)
